version: '3.6'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=blogs_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
